### PR TITLE
add supporting for vxWorks

### PR DESCRIPTION
**Pull request by BaoshanPang**
r? @gnzlbg

### CODE REVIEW

**Comment by BaoshanPang** [comment]
cc @n-salim
cc @maya-cm
cc @UmeshKalappa

**Comment by gnzlbg** [comment]
Thanks!

**Comment by gnzlbg** [comment]
Published 0.2.21 with this change.

**Comment by BaoshanPang** [comment]
> Published 0.2.21 with this change.

Thank you!

**Pull request merged**
